version: "3.7"
services:
  pauperial:
    image: registry.main.lwjerri.dev/lwjerri/pauperial
    networks:
      - caddy
    labels:
      caddy: pauperial.main.lwjerri.dev
      caddy.reverse_proxy: "{{upstreams 4000}}"

networks:
  caddy:
    external: true
