name: CI & CD

on:
  pull_request:
    branches:
      - "production"

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/lwjerri/pauperial:latest
      - name: Start Deployment
        run: |
          cd /root/services/pauperial
          docker compose pull
          docker compose up -d
